version: "3.8"

services:
    database:
        container_name: database_cliente
        image: postgres:12
        ports:
            - ${DATABASE_PORT}:${DATABASE_PORT}
        environment:
            POSTGRES_DB: ${DATABASE_NAME}
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_PASSWORD: ${DATABASE_PASS}
            TZ: ${TIMEZONE}
            PGTZ: ${TIMEZONE}
        volumes:
            - database_data:/var/lib/postgresql/data
volumes:
    database_data: